# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 560387fbaebebb0727d1fafef1eaf068ced4a14cd1dc9f24657eae6be56be856814baba339c3b072cd7f3e627904638db44af55c50f47ecfcf002be9cce02c94

test:
  secret_key_base: 29698a536c25a599a3a6789c409e197b540e7e9f9693fccc8a169f53f396b8ce8d36f8f1b0034998ea6f3b5046730c6570a640ea00b4a9949250eda87fd0416b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
